CREATE TABLE [dbo].[VENTA]
(
[IDVENT] [int] NOT NULL IDENTITY(1, 1),
[FECVEN] [date] NULL,
[ESTVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[IDPER] [int] NULL,
[IDPRO] [int] NULL,
[IDSUC] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [PK__VENTA__EA67554561061744] PRIMARY KEY CLUSTERED  ([IDVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_PRODUCTO_IDPRO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTOS] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_SUCURSAL_IDSUC] FOREIGN KEY ([IDSUC]) REFERENCES [dbo].[SUCURSAL] ([IDSUC])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_SUCURSAL_ISPER] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
