CREATE TABLE [dbo].[PRODUCTOS]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[PREPRO] [decimal] (3, 0) NULL,
[CATEGO] [char] (2) COLLATE Modern_Spanish_CI_AS NULL,
[CANPRO] [int] NULL,
[FECVEN] [date] NULL,
[ESTPRO] [varchar] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTOS] ADD CONSTRAINT [PK__PRODUCTO__98FA2D91EC2B84E1] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
