CREATE TABLE [dbo].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[DIRSUC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[NUMSUC] [int] NULL,
[ESTSUC] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[IDPER] [int] NULL,
[IDPRO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [PK__SUCURSAL__A5C81E91FB3A1117] PRIMARY KEY CLUSTERED  ([IDSUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_PERSONA_IDPER] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_PRODUCTOS_IDPRO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTOS] ([IDPRO])
GO
